services:
  - type: web
    name: checkwise-ai
    env: python
    plan: free
    buildCommand: |
      echo "Current directory: $(pwd)"
      ls -la
      pip install --upgrade pip
      pip install -r requirements.txt
      python build.py
    startCommand: gunicorn main:app --bind=0.0.0.0:$PORT --workers=1 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"