services:
  - type: web
    name: diagnosisai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
    region: ohio
    branch: main
    healthCheckPath: /api/health
    plan: free