# render.toml
# This file has higher priority than render.yaml and dashboard settings

[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && python build.py"

[start]
  command = "gunicorn main:app --bind=0.0.0.0:$PORT --workers=1 --timeout=120"

[env]
  PYTHON_VERSION = "3.9.0"
  PORT = "10000"