services:
  - type: web
    name: checkwise-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python build.py
    startCommand: gunicorn main:app --host=0.0.0.0 --port=$PORT --workers=1 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: PORT
        value: "10000"